### ISSUE TITLE
reboot chaos monkey

### ISSUE THREAD

**Issue by philips** [coreos/ktestutil#5]
@crawford worked on a tool that uses locksmithctl to reboot a machine from a pod. Might be a useful chaos monkey

See https://quay.io/repository/crawford/reboot/image/e646f44b74f65aeb9efb51798f69057d6a083d7968d785c68dcadec8d0d66faf

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: reboot
spec:
  template:
    metadata:
      labels:
        name: reboot
    spec:
      containers:
        - name: reboot
          image: quay.io/crawford/reboot
          volumeMounts:
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus
      volumes:
        - name: dbus
          hostPath:
            path: /var/run/dbus/system_bus_socket
```
